/**
 * 손으로 쓴 API 타입(`./index.ts`)이 백엔드 스키마에서 생성된 타입(`./api.generated.ts`)과
 * 필드 이름이 어긋나면 `tsc`가 실패하도록 하는 타입 전용 가드 (런타임 코드 없음, 어디서도 import하지 않음).
 * CI `api-types-drift` 잡은 생성 파일 ↔ 백엔드만 비교하므로, 백엔드에 필드를 추가/삭제하고
 * `npm run generate:api-types`만 돌린 채 손 타입을 안 고치면 이 파일이 잡아낸다.
 *
 * 필드 "이름"만 비교한다 — 생성 타입은 백엔드 기본값이 있는 응답 필드를 optional(`?`)로 표시해서
 * optional 여부까지 비교하면 오탐이 많다. 새 손 타입을 추가하면 아래 목록에도 한 줄 추가한다.
 */
import type { components } from "./api.generated";
import type {
  AccountCreateIn,
  AccountOut,
  AccountUpdateIn,
  AccountWithBalanceOut,
  AnnualCategoryBudgetRowOut,
  AnnualPlanItemMonthlyTargetIn,
  AnnualPlanItemMonthlyTargetOut,
  AnnualPlanItemOut,
  AnnualPlanItemUpsertIn,
  AnnualPlanListOut,
  AnnualPlanSectionMonthOut,
  AnnualPlanSectionSummaryOut,
  AnnualPlanSummaryOut,
  BudgetRowOut,
  BulkDeleteResultOut,
  CashflowPlanCopyResultOut,
  CashflowPlanItemOut,
  CashflowPlanItemSplitIn,
  CashflowPlanItemUpsertIn,
  CashflowPlanLinkRecurringIn,
  CashflowPlanListOut,
  CashflowPlanSectionSummaryOut,
  CashflowPlanSplitResultOut,
  CashflowPlanSummaryOut,
  CategoryAmountOut,
  CategoryBenchmarkRowOut,
  CategoryCreateIn,
  CategoryOut,
  CategoryTrendOut,
  CategoryTrendSeriesOut,
  CoachingThresholdsOut,
  DashboardBootstrapOut,
  DashboardOut,
  EventCreateIn,
  EventImportResultOut,
  EventListOut,
  EventOut,
  FinancialGoalCreateIn,
  FinancialGoalOut,
  FundingSourceIn,
  FundingSourceOut,
  GoalMonthlyTargetIn,
  GoalMonthlyTargetOut,
  GrowlioAccountOut,
  GrowlioGoalSettingsOut,
  GoalCheerIn,
  GoalCheerOut,
  GrowlioPerformanceOut,
  GrowlioDepositGuideOut,
  GrowlioFeasibilityOut,
  GrowlioGoalInsightOut,
  GrowlioRealEstateOut,
  GrowlioSyncAllOut,
  GrowlioSyncFailureOut,
  ImportResultOut,
  InsightOut,
  InviteAcceptIn,
  InviteOut,
  LoanCreateIn,
  LoanOut,
  MonthlyRetrospectiveOut,
  NetWorthBreakdownOut,
  NetWorthGrowlioUnlinkedOut,
  NetWorthOut,
  NetWorthSnapshotOut,
  NotificationListOut,
  NotificationOut,
  NotificationPrefsOut,
  NotificationReactionOut,
  NotifyEmailsIn,
  OwnerOverspendHighlightOut,
  OwnerTotalsOut,
  PaymentMethodAmountOut,
  RealEstateImportResultOut,
  RecurringCreateIn,
  RecurringListOut,
  RecurringOut,
  RecurringUpdateIn,
  SavingsProductAnnualPlanDetailOut,
  SavingsProductAnnualPlanGroupOut,
  SavingsProductAnnualPlanItemOut,
  SavingsProductAnnualPlanListOut,
  SavingsProductAnnualPlanMonthlyTargetIn,
  SavingsProductAnnualPlanMonthlyTargetOut,
  SavingsProductAnnualPlanUpsertIn,
  SavingsProductCreateIn,
  SavingsProductGrowlioLinkIn,
  SavingsProductOut,
  SavingsProductPlanGroupOut,
  SavingsProductPlanItemOut,
  SavingsProductPlanListOut,
  SettingsOut,
  SheetImportIn,
  SkippedRowOut,
  SurplusAllocationOut,
  TestEmailResultOut,
  TotalsOut,
  TransactionCreateIn,
  TransactionListOut,
  TransactionOut,
  TrendRowOut,
  UserOut,
  YearlyMonthRowOut,
  YearlyReportOut,
} from "./index";

type Schemas = components["schemas"];

type SameKeys<A, B> = [Exclude<keyof A, keyof B>, Exclude<keyof B, keyof A>] extends [never, never]
  ? true
  : { onlyInHandWritten: Exclude<keyof A, keyof B>; onlyInGenerated: Exclude<keyof B, keyof A> };
type Expect<T extends true> = T;

export type HandWrittenApiTypeChecks = [
  Expect<SameKeys<UserOut, Schemas["UserOut"]>>,
  Expect<SameKeys<InviteOut, Schemas["InviteOut"]>>,
  Expect<SameKeys<InviteAcceptIn, Schemas["InviteAcceptIn"]>>,
  Expect<SameKeys<CategoryOut, Schemas["CategoryOut"]>>,
  Expect<SameKeys<CategoryCreateIn, Schemas["CategoryCreateIn"]>>,
  Expect<SameKeys<AccountOut, Schemas["AccountOut"]>>,
  Expect<SameKeys<AccountWithBalanceOut, Schemas["AccountWithBalanceOut"]>>,
  Expect<SameKeys<AccountCreateIn, Schemas["AccountCreateIn"]>>,
  Expect<SameKeys<AccountUpdateIn, Schemas["AccountUpdateIn"]>>,
  Expect<SameKeys<TotalsOut, Schemas["TotalsOut"]>>,
  Expect<SameKeys<OwnerTotalsOut, Schemas["OwnerTotalsOut"]>>,
  Expect<SameKeys<CategoryAmountOut, Schemas["CategoryAmountOut"]>>,
  Expect<SameKeys<TrendRowOut, Schemas["TrendRowOut"]>>,
  Expect<SameKeys<InsightOut, Schemas["InsightOut"]>>,
  Expect<SameKeys<OwnerOverspendHighlightOut, Schemas["OwnerOverspendHighlightOut"]>>,
  Expect<SameKeys<PaymentMethodAmountOut, Schemas["PaymentMethodAmountOut"]>>,
  Expect<SameKeys<DashboardOut, Schemas["DashboardOut"]>>,
  Expect<SameKeys<SurplusAllocationOut, Schemas["SurplusAllocationOut"]>>,
  Expect<SameKeys<DashboardBootstrapOut, Schemas["DashboardBootstrapOut"]>>,
  Expect<SameKeys<MonthlyRetrospectiveOut, Schemas["MonthlyRetrospectiveOut"]>>,
  Expect<SameKeys<TransactionOut, Schemas["TransactionOut"]>>,
  Expect<SameKeys<TransactionCreateIn, Schemas["TransactionCreateIn"]>>,
  Expect<SameKeys<TransactionListOut, Schemas["TransactionListOut"]>>,
  Expect<SameKeys<SkippedRowOut, Schemas["SkippedRowOut"]>>,
  Expect<SameKeys<ImportResultOut, Schemas["ImportResultOut"]>>,
  Expect<SameKeys<SheetImportIn, Schemas["SheetImportIn"]>>,
  Expect<SameKeys<BulkDeleteResultOut, Schemas["BulkDeleteResultOut"]>>,
  Expect<SameKeys<RecurringOut, Schemas["RecurringOut"]>>,
  Expect<SameKeys<RecurringListOut, Schemas["RecurringListOut"]>>,
  Expect<SameKeys<RecurringCreateIn, Schemas["RecurringCreateIn"]>>,
  Expect<SameKeys<RecurringUpdateIn, Schemas["RecurringUpdateIn"]>>,
  Expect<SameKeys<YearlyMonthRowOut, Schemas["YearlyMonthRowOut"]>>,
  Expect<SameKeys<CategoryBenchmarkRowOut, Schemas["CategoryBenchmarkRowOut"]>>,
  Expect<SameKeys<YearlyReportOut, Schemas["YearlyReportOut"]>>,
  Expect<SameKeys<CategoryTrendSeriesOut, Schemas["CategoryTrendSeriesOut"]>>,
  Expect<SameKeys<CategoryTrendOut, Schemas["CategoryTrendOut"]>>,
  Expect<SameKeys<EventOut, Schemas["EventOut"]>>,
  Expect<SameKeys<EventListOut, Schemas["EventListOut"]>>,
  Expect<SameKeys<EventImportResultOut, Schemas["EventImportResultOut"]>>,
  Expect<SameKeys<EventCreateIn, Schemas["EventCreateIn"]>>,
  Expect<SameKeys<CoachingThresholdsOut, Schemas["CoachingThresholdsOut"]>>,
  Expect<SameKeys<NotificationPrefsOut, Schemas["NotificationPrefsOut"]>>,
  Expect<SameKeys<SettingsOut, Schemas["SettingsOut"]>>,
  Expect<SameKeys<NotifyEmailsIn, Schemas["NotifyEmailsIn"]>>,
  Expect<SameKeys<TestEmailResultOut, Schemas["TestEmailResultOut"]>>,
  Expect<SameKeys<CashflowPlanItemOut, Schemas["CashflowPlanItemOut"]>>,
  Expect<SameKeys<CashflowPlanItemUpsertIn, Schemas["CashflowPlanItemUpsertIn"]>>,
  Expect<SameKeys<CashflowPlanItemSplitIn, Schemas["CashflowPlanItemSplitIn"]>>,
  Expect<SameKeys<CashflowPlanSplitResultOut, Schemas["CashflowPlanSplitResultOut"]>>,
  Expect<SameKeys<CashflowPlanSectionSummaryOut, Schemas["CashflowPlanSectionSummaryOut"]>>,
  Expect<SameKeys<CashflowPlanSummaryOut, Schemas["CashflowPlanSummaryOut"]>>,
  Expect<SameKeys<CashflowPlanListOut, Schemas["CashflowPlanListOut"]>>,
  Expect<SameKeys<CashflowPlanCopyResultOut, Schemas["CashflowPlanCopyResultOut"]>>,
  Expect<SameKeys<CashflowPlanLinkRecurringIn, Schemas["CashflowPlanLinkRecurringIn"]>>,
  Expect<SameKeys<NotificationReactionOut, Schemas["NotificationReactionOut"]>>,
  Expect<SameKeys<NotificationOut, Schemas["NotificationOut"]>>,
  Expect<SameKeys<NotificationListOut, Schemas["NotificationListOut"]>>,
  Expect<SameKeys<FundingSourceOut, Schemas["FundingSourceOut"]>>,
  Expect<SameKeys<FundingSourceIn, Schemas["FundingSourceIn"]>>,
  Expect<SameKeys<GoalMonthlyTargetOut, Schemas["GoalMonthlyTargetOut"]>>,
  Expect<SameKeys<GoalMonthlyTargetIn, Schemas["GoalMonthlyTargetIn"]>>,
  Expect<SameKeys<FinancialGoalOut, Schemas["FinancialGoalOut"]>>,
  Expect<SameKeys<FinancialGoalCreateIn, Schemas["FinancialGoalCreateIn"]>>,
  Expect<SameKeys<GrowlioGoalSettingsOut, Schemas["GrowlioGoalSettingsOut"]>>,
  Expect<SameKeys<GoalCheerIn, Schemas["GoalCheerIn"]>>,
  Expect<SameKeys<GoalCheerOut, Schemas["GoalCheerOut"]>>,
  Expect<SameKeys<GrowlioPerformanceOut, Schemas["GrowlioPerformanceOut"]>>,
  Expect<SameKeys<GrowlioDepositGuideOut, Schemas["GrowlioDepositGuideOut"]>>,
  Expect<SameKeys<GrowlioFeasibilityOut, Schemas["GrowlioFeasibilityOut"]>>,
  Expect<SameKeys<GrowlioGoalInsightOut, Schemas["GrowlioGoalInsightOut"]>>,
  Expect<SameKeys<AnnualPlanItemMonthlyTargetOut, Schemas["AnnualPlanItemMonthlyTargetOut"]>>,
  Expect<SameKeys<AnnualPlanItemMonthlyTargetIn, Schemas["AnnualPlanItemMonthlyTargetIn"]>>,
  Expect<SameKeys<AnnualPlanItemOut, Schemas["AnnualPlanItemOut"]>>,
  Expect<SameKeys<AnnualPlanItemUpsertIn, Schemas["AnnualPlanItemUpsertIn"]>>,
  Expect<SameKeys<AnnualPlanSectionMonthOut, Schemas["AnnualPlanSectionMonthOut"]>>,
  Expect<SameKeys<AnnualPlanSectionSummaryOut, Schemas["AnnualPlanSectionSummaryOut"]>>,
  Expect<SameKeys<AnnualPlanSummaryOut, Schemas["AnnualPlanSummaryOut"]>>,
  Expect<SameKeys<AnnualPlanListOut, Schemas["AnnualPlanListOut"]>>,
  Expect<SameKeys<AnnualCategoryBudgetRowOut, Schemas["AnnualCategoryBudgetRowOut"]>>,
  Expect<SameKeys<SavingsProductOut, Schemas["SavingsProductOut"]>>,
  Expect<SameKeys<SavingsProductCreateIn, Schemas["SavingsProductCreateIn"]>>,
  Expect<SameKeys<SavingsProductGrowlioLinkIn, Schemas["SavingsProductGrowlioLinkIn"]>>,
  Expect<SameKeys<SavingsProductPlanItemOut, Schemas["SavingsProductPlanItemOut"]>>,
  Expect<SameKeys<SavingsProductPlanGroupOut, Schemas["SavingsProductPlanGroupOut"]>>,
  Expect<SameKeys<SavingsProductPlanListOut, Schemas["SavingsProductPlanListOut"]>>,
  Expect<SameKeys<SavingsProductAnnualPlanItemOut, Schemas["SavingsProductAnnualPlanItemOut"]>>,
  Expect<SameKeys<SavingsProductAnnualPlanGroupOut, Schemas["SavingsProductAnnualPlanGroupOut"]>>,
  Expect<SameKeys<SavingsProductAnnualPlanListOut, Schemas["SavingsProductAnnualPlanListOut"]>>,
  Expect<SameKeys<SavingsProductAnnualPlanMonthlyTargetOut, Schemas["SavingsProductAnnualPlanMonthlyTargetOut"]>>,
  Expect<SameKeys<SavingsProductAnnualPlanMonthlyTargetIn, Schemas["SavingsProductAnnualPlanMonthlyTargetIn"]>>,
  Expect<SameKeys<SavingsProductAnnualPlanDetailOut, Schemas["SavingsProductAnnualPlanDetailOut"]>>,
  Expect<SameKeys<SavingsProductAnnualPlanUpsertIn, Schemas["SavingsProductAnnualPlanUpsertIn"]>>,
  Expect<SameKeys<GrowlioAccountOut, Schemas["GrowlioAccountOut"]>>,
  Expect<SameKeys<GrowlioSyncFailureOut, Schemas["GrowlioSyncFailureOut"]>>,
  Expect<SameKeys<GrowlioSyncAllOut, Schemas["GrowlioSyncAllOut"]>>,
  Expect<SameKeys<GrowlioRealEstateOut, Schemas["GrowlioRealEstateOut"]>>,
  Expect<SameKeys<RealEstateImportResultOut, Schemas["RealEstateImportResultOut"]>>,
  Expect<SameKeys<LoanOut, Schemas["LoanOut"]>>,
  Expect<SameKeys<LoanCreateIn, Schemas["LoanCreateIn"]>>,
  Expect<SameKeys<NetWorthBreakdownOut, Schemas["NetWorthBreakdownOut"]>>,
  Expect<SameKeys<NetWorthSnapshotOut, Schemas["NetWorthSnapshotOut"]>>,
  Expect<SameKeys<NetWorthOut, Schemas["NetWorthOut"]>>,
  Expect<SameKeys<NetWorthGrowlioUnlinkedOut, Schemas["NetWorthGrowlioUnlinkedOut"]>>,
  Expect<SameKeys<BudgetRowOut, Schemas["CategoryBudgetRowOut"]>>,
];
