"""squashed_baseline

기존 51개 선형 체인(9e12ea51685e … b8f2a1c9e4d7)을 접은 새 단일 베이스라인.
아카이브된 원본은 migrations/versions/_archive/ 에 있다.

검증(임시 PostgreSQL 16, pgserver): 구 체인 `upgrade head` 의 `pg_dump --schema-only`
결과와 이 베이스라인만 적용한 결과가 오브젝트 단위로 완전히 일치하며, 이 베이스라인에서
`alembic revision --autogenerate` 가 빈 마이그레이션을 만든다. 그 과정에서 드러난
모델↔마이그레이션 드리프트(인덱스 7개, FK 제약 이름 8개, 컬럼 server_default 9개)는
모델 쪽을 운영 스키마에 맞춰 정합화했다.

운영 전환: 배포 담당자가 배포 전 운영 DB에 `alembic stamp bdba3c3b3277` 를 1회 실행한다
(빠뜨리면 `alembic upgrade head` 가 CREATE TABLE 충돌로 실패). 롤백은 이전 이미지 재배포 +
`alembic stamp b8f2a1c9e4d7`.

Revision ID: bdba3c3b3277
Revises:
Create Date: 2026-09-01 12:22:37.540996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdba3c3b3277'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 구 initial_schema(9e12ea51685e)와 동일하게, 스키마가 없으면 만든다. 운영 Supabase에는
    # 이미 존재하므로 no-op이고, 빈 DB에 처음 올릴 때만 실제로 생성된다.
    op.execute("CREATE SCHEMA IF NOT EXISTS household")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='expense', nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_discretionary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_debt', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_savings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('benchmark_group', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('google_oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('token_uri', sa.String(length=200), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('accounts_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('savings_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loans_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_month'),
    schema='household'
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notif_type', sa.String(length=30), nullable=False),
    sa.Column('related_type', sa.String(length=30), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('year_month', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('removed_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['removed_by_id'], ['household.users.id'], name='fk_users_removed_by_id_users'),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    with op.batch_alter_table('users', schema='household') as batch_op:
        batch_op.create_index(batch_op.f('ix_household_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('growlio_account_id', sa.String(length=36), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('annual_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('start_month', sa.String(length=7), nullable=False),
    sa.Column('end_month', sa.String(length=7), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['household.categories.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['household.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='native', nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['household.users.id'], name='fk_events_assignee_id_users'),
    sa.ForeignKeyConstraint(['created_by'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('financial_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('target_age', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('required_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_saving_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    with op.batch_alter_table('invites', schema='household') as batch_op:
        batch_op.create_index(batch_op.f('ix_household_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_invites_token'), ['token'], unique=True)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('origination_year_month', sa.String(length=7), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('repayment_method', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('growlio_account_id', sa.String(length=36), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('notification_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_log_id'], ['household.notification_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_log_id', 'user_id', name='uq_notification_reaction_log_user'),
    schema='household'
    )
    with op.batch_alter_table('notification_reaction', schema='household') as batch_op:
        batch_op.create_index(batch_op.f('ix_household_notification_reaction_notification_log_id'), ['notification_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_notification_reaction_user_id'), ['user_id'], unique=False)

    op.create_table('notification_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_log_id'], ['household.notification_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_log_id', 'user_id', name='uq_notification_read_log_user'),
    schema='household'
    )
    with op.batch_alter_table('notification_read', schema='household') as batch_op:
        batch_op.create_index(batch_op.f('ix_household_notification_read_notification_log_id'), ['notification_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_notification_read_user_id'), ['user_id'], unique=False)

    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), server_default='expense', nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('days_of_month', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['household.categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('savings_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_saving_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_type', sa.String(length=20), server_default='savings', nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('growlio_account_id', sa.String(length=36), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_setting_key'),
    schema='household'
    )
    op.create_table('annual_plan_item_monthly_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['household.annual_plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'year_month', name='uq_annual_plan_item_monthly_target_month'),
    schema='household'
    )
    op.create_table('cashflow_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('installment_total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recurring_expense_id', sa.Integer(), nullable=True),
    sa.Column('annual_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annual_plan_item_id'], ['household.annual_plan_items.id'], name='fk_cashflow_plan_items_annual_plan_item_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['household.categories.id'], name='fk_cashflow_plan_items_category_id_categories'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['household.users.id'], ),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['household.recurring_expenses.id'], name='fk_cashflow_plan_items_recurring_expense_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    op.create_table('goal_funding_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('savings_product_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN savings_product_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN account_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN loan_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_goal_funding_source_exactly_one_type'),
    sa.ForeignKeyConstraint(['account_id'], ['household.accounts.id'], name='fk_goal_funding_sources_account_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['household.financial_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['household.loans.id'], name='fk_goal_funding_sources_loan_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['savings_product_id'], ['household.savings_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'account_id', name='uq_goal_funding_source_account'),
    sa.UniqueConstraint('goal_id', 'loan_id', name='uq_goal_funding_source_loan'),
    sa.UniqueConstraint('goal_id', 'savings_product_id', name='uq_goal_funding_source'),
    sa.UniqueConstraint('savings_product_id', name='uq_goal_funding_source_savings_product_unique'),
    schema='household'
    )
    op.create_table('goal_monthly_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('achieved_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['household.financial_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'year_month', name='uq_goal_monthly_target_month'),
    schema='household'
    )
    op.create_table('savings_product_annual_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.String(length=7), nullable=False),
    sa.Column('end_month', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['household.savings_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'year', name='uq_savings_product_annual_plan_year'),
    schema='household'
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('recurring_expense_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('savings_product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['household.accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['household.categories.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['household.users.id'], ),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['household.recurring_expenses.id'], ),
    sa.ForeignKeyConstraint(['savings_product_id'], ['household.savings_products.id'], name='fk_transactions_savings_product_id_savings_products'),
    sa.ForeignKeyConstraint(['user_id'], ['household.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='household'
    )
    with op.batch_alter_table('transactions', schema='household') as batch_op:
        batch_op.create_index(batch_op.f('ix_household_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('savings_product_annual_plan_monthly_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['household.savings_product_annual_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'year_month', name='uq_savings_product_annual_plan_monthly_target_month'),
    schema='household'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_product_annual_plan_monthly_targets', schema='household')
    with op.batch_alter_table('transactions', schema='household') as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_household_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_household_transactions_account_id'))

    op.drop_table('transactions', schema='household')
    op.drop_table('savings_product_annual_plans', schema='household')
    op.drop_table('goal_monthly_targets', schema='household')
    op.drop_table('goal_funding_sources', schema='household')
    op.drop_table('cashflow_plan_items', schema='household')
    op.drop_table('annual_plan_item_monthly_targets', schema='household')
    op.drop_table('user_settings', schema='household')
    op.drop_table('savings_products', schema='household')
    op.drop_table('recurring_expenses', schema='household')
    with op.batch_alter_table('notification_read', schema='household') as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_notification_read_user_id'))
        batch_op.drop_index(batch_op.f('ix_household_notification_read_notification_log_id'))

    op.drop_table('notification_read', schema='household')
    with op.batch_alter_table('notification_reaction', schema='household') as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_notification_reaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_household_notification_reaction_notification_log_id'))

    op.drop_table('notification_reaction', schema='household')
    op.drop_table('loans', schema='household')
    with op.batch_alter_table('invites', schema='household') as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_invites_token'))
        batch_op.drop_index(batch_op.f('ix_household_invites_email'))

    op.drop_table('invites', schema='household')
    op.drop_table('financial_goals', schema='household')
    op.drop_table('events', schema='household')
    op.drop_table('annual_plan_items', schema='household')
    op.drop_table('accounts', schema='household')
    with op.batch_alter_table('users', schema='household') as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_users_email'))

    op.drop_table('users', schema='household')
    op.drop_table('notification_log', schema='household')
    op.drop_table('net_worth_snapshots', schema='household')
    op.drop_table('google_oauth_tokens', schema='household')
    op.drop_table('categories', schema='household')
    # ### end Alembic commands ###
    # household 스키마 자체는 남긴다 - alembic_version 테이블이 이 스키마에 있어(env.py의
    # version_table_schema) DROP SCHEMA 는 실패하고, 빈 스키마는 무해하다.
